### ISSUE TITLE
Manifest parse error should not take down the whole site

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/wp-theme-init#6]
```

[Thu Dec 05 21:57:29.469846 2019] [php7:error] [pid 4586] [client 100.33.54.172:61418] PHP Fatal error: Uncaught Exception: Unable to decode manifest (error parsing JSON) in /nas/content/live/client01/wp-content/themes/theme-0_0_38/vendor/ideasonpurpose/wp-theme-init/src/Manifest.php:46
Stack trace:
#0 /nas/content/live/client01/wp-content/themes/theme-0_0_38/functions.php(68): ideasonpurpose\\ThemeInit\\Manifest->__construct('/nas/content/li...')
#1 /nas/content/live/client01/wp-settings.php(497): include('/nas/content/li...')
#2 /nas/content/live/client01/wp-config.php(119): require_once('/nas/content/li...')
#3 /nas/content/live/client01/wp-load.php(37): require_once('/nas/content/li...')
#4 /nas/content/live/client01/wp-admin/admin.php(34): require_once('/nas/content/li...')
#5 /nas/content/live/client01/wp-admin/index.php(10): require_once('/nas/content/li...')
#6 {main}
 thrown in /nas/content/live/client01/wp-content/themes/theme-0_0_38/vendor/ideasonpurpose/wp-theme-init/src/Manifest.php on line 46
--
```

**Comment by joemaller** [comment]
Closed in 0d44e8f096ada97da6aa681433a0dfa97e47e9ba
